//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34209
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDDOlaMundo.www.w3schools.com {
    
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="TDDOlaMundo.www.w3schools.com", ConfigurationName="TempConvertSoap")]
public interface TempConvertSoap {
    
    // CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (http://www.w3schools.com/webservices/) da mensagem FahrenheitToCelsiusRequest não corresponde ao valor padrão (TDDOlaMundo.www.w3schools.com)
    [System.ServiceModel.OperationContractAttribute(Action="http://www.w3schools.com/webservices/TempConvertSoap/FahrenheitToCelsiusRequest", ReplyAction="http://www.w3schools.com/webservices/TempConvertSoap/FahrenheitToCelsiusResponse")]
    FahrenheitToCelsiusResponse FahrenheitToCelsius(FahrenheitToCelsiusRequest request);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.w3schools.com/webservices/TempConvertSoap/FahrenheitToCelsiusRequest", ReplyAction="http://www.w3schools.com/webservices/TempConvertSoap/FahrenheitToCelsiusResponse")]
    System.IAsyncResult BeginFahrenheitToCelsius(FahrenheitToCelsiusRequest request, System.AsyncCallback callback, object asyncState);
    
    FahrenheitToCelsiusResponse EndFahrenheitToCelsius(System.IAsyncResult result);
    
    // CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (http://www.w3schools.com/webservices/) da mensagem CelsiusToFahrenheitRequest não corresponde ao valor padrão (TDDOlaMundo.www.w3schools.com)
    [System.ServiceModel.OperationContractAttribute(Action="http://www.w3schools.com/webservices/TempConvertSoap/CelsiusToFahrenheitRequest", ReplyAction="http://www.w3schools.com/webservices/TempConvertSoap/CelsiusToFahrenheitResponse")]
    CelsiusToFahrenheitResponse CelsiusToFahrenheit(CelsiusToFahrenheitRequest request);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.w3schools.com/webservices/TempConvertSoap/CelsiusToFahrenheitRequest", ReplyAction="http://www.w3schools.com/webservices/TempConvertSoap/CelsiusToFahrenheitResponse")]
    System.IAsyncResult BeginCelsiusToFahrenheit(CelsiusToFahrenheitRequest request, System.AsyncCallback callback, object asyncState);
    
    CelsiusToFahrenheitResponse EndCelsiusToFahrenheit(System.IAsyncResult result);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="FahrenheitToCelsius", WrapperNamespace="http://www.w3schools.com/webservices/", IsWrapped=true)]
public partial class FahrenheitToCelsiusRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3schools.com/webservices/", Order=0)]
    public string Fahrenheit;
    
    public FahrenheitToCelsiusRequest() {
    }
    
    public FahrenheitToCelsiusRequest(string Fahrenheit) {
        this.Fahrenheit = Fahrenheit;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="FahrenheitToCelsiusResponse", WrapperNamespace="http://www.w3schools.com/webservices/", IsWrapped=true)]
public partial class FahrenheitToCelsiusResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3schools.com/webservices/", Order=0)]
    public string FahrenheitToCelsiusResult;
    
    public FahrenheitToCelsiusResponse() {
    }
    
    public FahrenheitToCelsiusResponse(string FahrenheitToCelsiusResult) {
        this.FahrenheitToCelsiusResult = FahrenheitToCelsiusResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CelsiusToFahrenheit", WrapperNamespace="http://www.w3schools.com/webservices/", IsWrapped=true)]
public partial class CelsiusToFahrenheitRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3schools.com/webservices/", Order=0)]
    public string Celsius;
    
    public CelsiusToFahrenheitRequest() {
    }
    
    public CelsiusToFahrenheitRequest(string Celsius) {
        this.Celsius = Celsius;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CelsiusToFahrenheitResponse", WrapperNamespace="http://www.w3schools.com/webservices/", IsWrapped=true)]
public partial class CelsiusToFahrenheitResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3schools.com/webservices/", Order=0)]
    public string CelsiusToFahrenheitResult;
    
    public CelsiusToFahrenheitResponse() {
    }
    
    public CelsiusToFahrenheitResponse(string CelsiusToFahrenheitResult) {
        this.CelsiusToFahrenheitResult = CelsiusToFahrenheitResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface TempConvertSoapChannel : TempConvertSoap, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TempConvertSoapClient : System.ServiceModel.ClientBase<TempConvertSoap>, TempConvertSoap {
    
    public TempConvertSoapClient() {
    }
    
    public TempConvertSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public TempConvertSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public TempConvertSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public TempConvertSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    FahrenheitToCelsiusResponse TempConvertSoap.FahrenheitToCelsius(FahrenheitToCelsiusRequest request) {
        return base.Channel.FahrenheitToCelsius(request);
    }
    
    public string FahrenheitToCelsius(string Fahrenheit) {
        FahrenheitToCelsiusRequest inValue = new FahrenheitToCelsiusRequest();
        inValue.Fahrenheit = Fahrenheit;
        FahrenheitToCelsiusResponse retVal = ((TempConvertSoap)(this)).FahrenheitToCelsius(inValue);
        return retVal.FahrenheitToCelsiusResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult TempConvertSoap.BeginFahrenheitToCelsius(FahrenheitToCelsiusRequest request, System.AsyncCallback callback, object asyncState) {
        return base.Channel.BeginFahrenheitToCelsius(request, callback, asyncState);
    }
    
    public System.IAsyncResult BeginFahrenheitToCelsius(string Fahrenheit, System.AsyncCallback callback, object asyncState) {
        FahrenheitToCelsiusRequest inValue = new FahrenheitToCelsiusRequest();
        inValue.Fahrenheit = Fahrenheit;
        return ((TempConvertSoap)(this)).BeginFahrenheitToCelsius(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    FahrenheitToCelsiusResponse TempConvertSoap.EndFahrenheitToCelsius(System.IAsyncResult result) {
        return base.Channel.EndFahrenheitToCelsius(result);
    }
    
    public string EndFahrenheitToCelsius(System.IAsyncResult result) {
        FahrenheitToCelsiusResponse retVal = ((TempConvertSoap)(this)).EndFahrenheitToCelsius(result);
        return retVal.FahrenheitToCelsiusResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CelsiusToFahrenheitResponse TempConvertSoap.CelsiusToFahrenheit(CelsiusToFahrenheitRequest request) {
        return base.Channel.CelsiusToFahrenheit(request);
    }
    
    public string CelsiusToFahrenheit(string Celsius) {
        CelsiusToFahrenheitRequest inValue = new CelsiusToFahrenheitRequest();
        inValue.Celsius = Celsius;
        CelsiusToFahrenheitResponse retVal = ((TempConvertSoap)(this)).CelsiusToFahrenheit(inValue);
        return retVal.CelsiusToFahrenheitResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult TempConvertSoap.BeginCelsiusToFahrenheit(CelsiusToFahrenheitRequest request, System.AsyncCallback callback, object asyncState) {
        return base.Channel.BeginCelsiusToFahrenheit(request, callback, asyncState);
    }
    
    public System.IAsyncResult BeginCelsiusToFahrenheit(string Celsius, System.AsyncCallback callback, object asyncState) {
        CelsiusToFahrenheitRequest inValue = new CelsiusToFahrenheitRequest();
        inValue.Celsius = Celsius;
        return ((TempConvertSoap)(this)).BeginCelsiusToFahrenheit(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CelsiusToFahrenheitResponse TempConvertSoap.EndCelsiusToFahrenheit(System.IAsyncResult result) {
        return base.Channel.EndCelsiusToFahrenheit(result);
    }
    
    public string EndCelsiusToFahrenheit(System.IAsyncResult result) {
        CelsiusToFahrenheitResponse retVal = ((TempConvertSoap)(this)).EndCelsiusToFahrenheit(result);
        return retVal.CelsiusToFahrenheitResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="TDDOlaMundo.www.w3schools.com", ConfigurationName="TempConvertHttpPost")]
public interface TempConvertHttpPost {
    
    // CODEGEN: Gerando contrato de mensagem porque a operação FahrenheitToCelsius não é RPC nem documento codificado.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.w3schools.com/webservices/TempConvertHttpPost/FahrenheitToCelsiusReque" +
        "st", ReplyAction="http://www.w3schools.com/webservices/TempConvertHttpPost/FahrenheitToCelsiusRespo" +
        "nse")]
    FahrenheitToCelsiusResponse1 FahrenheitToCelsius(FahrenheitToCelsiusRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.w3schools.com/webservices/TempConvertHttpPost/FahrenheitToCelsiusReque" +
        "st", ReplyAction="http://www.w3schools.com/webservices/TempConvertHttpPost/FahrenheitToCelsiusRespo" +
        "nse")]
    System.IAsyncResult BeginFahrenheitToCelsius(FahrenheitToCelsiusRequest1 request, System.AsyncCallback callback, object asyncState);
    
    FahrenheitToCelsiusResponse1 EndFahrenheitToCelsius(System.IAsyncResult result);
    
    // CODEGEN: Gerando contrato de mensagem porque a operação CelsiusToFahrenheit não é RPC nem documento codificado.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.w3schools.com/webservices/TempConvertHttpPost/CelsiusToFahrenheitReque" +
        "st", ReplyAction="http://www.w3schools.com/webservices/TempConvertHttpPost/CelsiusToFahrenheitRespo" +
        "nse")]
    CelsiusToFahrenheitResponse1 CelsiusToFahrenheit(CelsiusToFahrenheitRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.w3schools.com/webservices/TempConvertHttpPost/CelsiusToFahrenheitReque" +
        "st", ReplyAction="http://www.w3schools.com/webservices/TempConvertHttpPost/CelsiusToFahrenheitRespo" +
        "nse")]
    System.IAsyncResult BeginCelsiusToFahrenheit(CelsiusToFahrenheitRequest1 request, System.AsyncCallback callback, object asyncState);
    
    CelsiusToFahrenheitResponse1 EndCelsiusToFahrenheit(System.IAsyncResult result);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class FahrenheitToCelsiusRequest1 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string Fahrenheit;
    
    public FahrenheitToCelsiusRequest1() {
    }
    
    public FahrenheitToCelsiusRequest1(string Fahrenheit) {
        this.Fahrenheit = Fahrenheit;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class FahrenheitToCelsiusResponse1 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3schools.com/webservices/", Order=0)]
    public string @string;
    
    public FahrenheitToCelsiusResponse1() {
    }
    
    public FahrenheitToCelsiusResponse1(string @string) {
        this.@string = @string;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CelsiusToFahrenheitRequest1 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string Celsius;
    
    public CelsiusToFahrenheitRequest1() {
    }
    
    public CelsiusToFahrenheitRequest1(string Celsius) {
        this.Celsius = Celsius;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CelsiusToFahrenheitResponse1 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3schools.com/webservices/", Order=0)]
    public string @string;
    
    public CelsiusToFahrenheitResponse1() {
    }
    
    public CelsiusToFahrenheitResponse1(string @string) {
        this.@string = @string;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface TempConvertHttpPostChannel : TempConvertHttpPost, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TempConvertHttpPostClient : System.ServiceModel.ClientBase<TempConvertHttpPost>, TempConvertHttpPost {
    
    public TempConvertHttpPostClient() {
    }
    
    public TempConvertHttpPostClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public TempConvertHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public TempConvertHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public TempConvertHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    FahrenheitToCelsiusResponse1 TempConvertHttpPost.FahrenheitToCelsius(FahrenheitToCelsiusRequest1 request) {
        return base.Channel.FahrenheitToCelsius(request);
    }
    
    public string FahrenheitToCelsius(string Fahrenheit) {
        FahrenheitToCelsiusRequest1 inValue = new FahrenheitToCelsiusRequest1();
        inValue.Fahrenheit = Fahrenheit;
        FahrenheitToCelsiusResponse1 retVal = ((TempConvertHttpPost)(this)).FahrenheitToCelsius(inValue);
        return retVal.@string;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult TempConvertHttpPost.BeginFahrenheitToCelsius(FahrenheitToCelsiusRequest1 request, System.AsyncCallback callback, object asyncState) {
        return base.Channel.BeginFahrenheitToCelsius(request, callback, asyncState);
    }
    
    public System.IAsyncResult BeginFahrenheitToCelsius(string Fahrenheit, System.AsyncCallback callback, object asyncState) {
        FahrenheitToCelsiusRequest1 inValue = new FahrenheitToCelsiusRequest1();
        inValue.Fahrenheit = Fahrenheit;
        return ((TempConvertHttpPost)(this)).BeginFahrenheitToCelsius(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    FahrenheitToCelsiusResponse1 TempConvertHttpPost.EndFahrenheitToCelsius(System.IAsyncResult result) {
        return base.Channel.EndFahrenheitToCelsius(result);
    }
    
    public string EndFahrenheitToCelsius(System.IAsyncResult result) {
        FahrenheitToCelsiusResponse1 retVal = ((TempConvertHttpPost)(this)).EndFahrenheitToCelsius(result);
        return retVal.@string;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CelsiusToFahrenheitResponse1 TempConvertHttpPost.CelsiusToFahrenheit(CelsiusToFahrenheitRequest1 request) {
        return base.Channel.CelsiusToFahrenheit(request);
    }
    
    public string CelsiusToFahrenheit(string Celsius) {
        CelsiusToFahrenheitRequest1 inValue = new CelsiusToFahrenheitRequest1();
        inValue.Celsius = Celsius;
        CelsiusToFahrenheitResponse1 retVal = ((TempConvertHttpPost)(this)).CelsiusToFahrenheit(inValue);
        return retVal.@string;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult TempConvertHttpPost.BeginCelsiusToFahrenheit(CelsiusToFahrenheitRequest1 request, System.AsyncCallback callback, object asyncState) {
        return base.Channel.BeginCelsiusToFahrenheit(request, callback, asyncState);
    }
    
    public System.IAsyncResult BeginCelsiusToFahrenheit(string Celsius, System.AsyncCallback callback, object asyncState) {
        CelsiusToFahrenheitRequest1 inValue = new CelsiusToFahrenheitRequest1();
        inValue.Celsius = Celsius;
        return ((TempConvertHttpPost)(this)).BeginCelsiusToFahrenheit(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CelsiusToFahrenheitResponse1 TempConvertHttpPost.EndCelsiusToFahrenheit(System.IAsyncResult result) {
        return base.Channel.EndCelsiusToFahrenheit(result);
    }
    
    public string EndCelsiusToFahrenheit(System.IAsyncResult result) {
        CelsiusToFahrenheitResponse1 retVal = ((TempConvertHttpPost)(this)).EndCelsiusToFahrenheit(result);
        return retVal.@string;
    }
}
